### ISSUE TITLE
Crash on getPrintStatus after Printing Label

### ISSUE THREAD

**Issue by Svalasky** [andresperezmelo/niimbot_label_printer#4]
`E/AndroidRuntime(26909): FATAL EXCEPTION: DefaultDispatcher-worker-3
E/AndroidRuntime(26909): Process: com.example.smart_fault, PID: 26909
E/AndroidRuntime(26909): java.lang.IndexOutOfBoundsException: toIndex (2) is greater than size (1).
E/AndroidRuntime(26909):        at kotlin.collections.ArraysKt__ArraysJVMKt.copyOfRangeToIndexCheck(ArraysJVM.kt:49)
E/AndroidRuntime(26909):        at kotlin.collections.ArraysKt___ArraysJvmKt.copyOfRange(_ArraysJvm.kt:1843)
E/AndroidRuntime(26909):        at com.example.niimbot_label_printer.NiimbotPrinter.getPrintStatus(NiimbotPrinter.kt:221)
E/AndroidRuntime(26909):        at com.example.niimbot_label_printer.NiimbotPrinter$getPrintStatus$1.invokeSuspend(Unknown Source:14)
E/AndroidRuntime(26909):        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(26909):        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime(26909):        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
E/AndroidRuntime(26909):        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
E/AndroidRuntime(26909):        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
E/AndroidRuntime(26909):        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
E/AndroidRuntime(26909):        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@8013e3b, Dispatchers.Default]`

After I print with the example code provided, the application always crashes and exits with this error

[√] Flutter (Channel stable, 3.24.4, on Microsoft Windows [Version 10.0.19045.5011], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[!] Android Studio (version 2021.3)
    X Unable to determine bundled Java version.
[!] Android Studio (version 2023.1)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2024.2)
[√] IntelliJ IDEA Community Edition (version 2022.3)
[√] VS Code (version 1.95.1)
[√] Connected device (4 available)
[√] Network resources

**Comment by MaretArt** [comment]
hi, i also have the same error.
have you solved it?
